openapi: 3.0.1
info:
  title: U2U-AI.API
  version: '1.0'
servers:
  - url: https://localhost:7250
paths: { }
components:
  schemas:
    Course:
      type: object
      properties:
        courseTitleSlug:
          type: string
          nullable: true
        courseTitle:
          type: string
          nullable: true
        numberOfDays:
          type: integer
          format: int32
        learningGoals:
          type: string
          nullable: true
        targetAudience:
          type: string
          nullable: true
        recommendationInfo:
          type: string
          nullable: true
          readOnly: true
        htmlFileName:
          type: string
          nullable: true
      additionalProperties: false
    Session:
      type: object
      properties:
        id:
          type: integer
          format: int32
        course:
          $ref: '#/components/schemas/Course'
        courseId:
          type: string
          nullable: true
        organisationDays:
          type: array
          items:
            type: string
            format: date
          nullable: true
      additionalProperties: false